language: java

jdk:
  - openjdk11

before_install:
  - echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin

stages:
  - test
  - name: publish
    if: type = push AND branch = master

jobs:
  include:
    - stage: test
      script: ./gradlew check
    - stage: publish
      script: ./gradlew clean bintrayUpload

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

services:
  - docker
